### ISSUE TITLE
Will the training code be released?

### ISSUE THREAD

**Issue by lijie2160** [FrozenBurning/SceneDreamer#2]
Good Job, Can I get the trainning code?

**Comment by FrozenBurning** [comment]
Sure. We'll be working on it in a few months.

**Comment by hanxuel** [comment]
Thank you for your excellent work, when will you release the training code?

**Comment by FrozenBurning** [comment]
We'll release the training code in about 2 months ideally as the paper is still under review. Thanks for your interest and patience 🍻

**Comment by jingfengguo-ai** [comment]
> We'll release the training code in about 2 months ideally as the paper is still under review. Thanks for your interest and patience 🍻

Thank you for your excellent work, when will you release the training code?

**Comment by FrozenBurning** [comment]
We've just released the training code! Thanks for your patience 🍻
