### ISSUE TITLE
How can I give new 2D images as input?

### ISSUE THREAD

**Issue by albusdemens** [FrozenBurning/SceneDreamer#3]
Hello, congratulations for the great work! How can I provide a new set of 2D images as an input? Thank you

**Comment by FrozenBurning** [comment]
Thanks for your interest in our work. Given a new set of 2D images that are out of the training distribution, you need to fine-tune the network. Stay tuned to our training code release 🍻

**Comment by albusdemens** [comment]
Thank you for letting me know! I'm looking forward for your release :)

**Comment by FrozenBurning** [comment]
The training code has been released!
