### ISSUE TITLE
HELP：Can I replace Colonmap and Heightmap to generate my own 3D scene?

### ISSUE THREAD

**Issue by Bean95zx** [FrozenBurning/SceneDreamer#4]
I want to replace the colormap and heightmap in the demo and use my own image to generate a 3D scene. Is that okay?

**Comment by FrozenBurning** [comment]
Sorry for missing your issue. The answer is yes! You can replace the semantic map and heightmap in the demo to generate the scene you like. For using your own images, I assume you refer to retrain the model in a different domain (e.g., different styles), please stay tuned to our training code instead.

**Comment by FrozenBurning** [comment]
Close due to inactivity. Feel free to reopen if you have any questions!
