### ISSUE TITLE
Ask a question

### ISSUE THREAD

**Issue by Doby6** [FrozenBurning/SceneDreamer#5]
May I ask if this can support Windows system deployment?

**Comment by FrozenBurning** [comment]
Good point! Unfortunately, we have no plan for windows development so far. And we're welcome any contribution from the community on this!

**Comment by FrozenBurning** [comment]
Close due to inactivity. Feel free to reopen if you have any question!

**Comment by yswweybsll** [comment]
Hello, does this currently support virtual machine deployment under the Windows system ?
