### ISSUE TITLE
How to get 3d models from the results? 

### ISSUE THREAD

**Issue by Hub-Tian** [FrozenBurning/SceneDreamer#7]
Wonderful work! But how to get the 3D models with a format like 'obj' from the results?

**Comment by FrozenBurning** [comment]
Thanks for your interest! You can get 3D mesh by either leveraging the marching cube algorithm on top of our neural renderer or performing dense reconstruction from the rendered trajectory.

**Comment by FrozenBurning** [comment]
Close due to inactivity. Feel free to reopen for further questions!

**Comment by zydmtaichi** [comment]
> Thanks for your interest! You can get 3D mesh by either leveraging the marching cube algorithm on top of our neural renderer or performing dense reconstruction from the rendered trajectory.

could you pls give some example for above?
