### ISSUE TITLE
About miss of the ./scripts/build_lmdb.py

### ISSUE THREAD

**Issue by winglicopy** [FrozenBurning/SceneDreamer#9]
I noticed that I have to convert images to imdb format before training SceneDreamer; however, I did not find the script ./scripts/build_lmdb.py that is used for converting.
![image](https://github.com/FrozenBurning/SceneDreamer/assets/113141241/8a63b15e-4583-418b-a511-c6e535429294)
![image](https://github.com/FrozenBurning/SceneDreamer/assets/113141241/b0b15e93-41dc-4d89-97fe-240f1c3ad911)

**Comment by FrozenBurning** [comment]
Thanks for your interest in our work and sorry for the confusion. I've uploaded the required script in the latest commit, check out and let me know if you have further questions!

**Comment by winglicopy** [comment]
it is solved by owner.
